"""Немного поменял названия таблиц

Revision ID: 60c601d59a93
Revises: 6cc967e05dd1
Create Date: 2025-02-11 10:35:27.392447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c601d59a93'
down_revision: Union[str, None] = '6cc967e05dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ignore_leads',
    sa.Column('id', sa.BIGINT(), nullable=False, comment='Айди аккаунта Teleagram'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ignore_leads_id'), 'ignore_leads', ['id'], unique=False)
    op.drop_index('ix_ignore_lead_id', table_name='ignore_lead')
    op.drop_table('ignore_lead')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ignore_lead',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ignore_lead_id', 'ignore_lead', ['id'], unique=False)
    op.drop_index(op.f('ix_ignore_leads_id'), table_name='ignore_leads')
    op.drop_table('ignore_leads')
    # ### end Alembic commands ###
