"""Создал бд с таблицей аккаунтов

Revision ID: 90301f6074b6
Revises: 
Create Date: 2025-02-03 18:19:11.747823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90301f6074b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.BIGINT(), nullable=False, comment='Айди аккаунта Teleagram'),
    sa.Column('phone_number', sa.String(), nullable=False, comment='номер телефона, привязанный к аккаунту.'),
    sa.Column('api_id', sa.BIGINT(), nullable=False, comment='параметр для аутентификации'),
    sa.Column('api_hash', sa.String(), nullable=False, comment='параметр для аутентификации'),
    sa.Column('_proxy', sa.JSON(), nullable=True, comment='прокси для аккаунта в формате JSON. Пример: {"scheme": "socks5", "hostname": "...", "port": 1234}'),
    sa.Column('session_string', sa.TEXT(), nullable=False, comment='Сессия в формате строки'),
    sa.Column('is_valid', sa.Boolean(), server_default='true', nullable=False, comment='валидная ли сессия или нет'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_phone_number'), 'accounts', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_phone_number'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
